version: '3.8'
services:

  api:
    build: .
    command: ["flask", "run", "--host", "0.0.0.0"]
    depends_on:
      - broker
      - tasks-caller
    env_file:
      - .example.api.env
    environment:
      FLASK_ENV: 'development'
    ports:
      - '5000:5000'
    volumes:
      - './api:/usr/src/app/api'

  broker:
    image: redis:6.0-alpine

  tasks-caller:
    build: .
