version: '3.8'
services:

  backend:
    build: .
    depends_on:
      - database
    env_file:
      - .example.env
    ports:
      - '8000:8000'
    volumes:
      - './site_parser:/usr/src/app/site_parser'

  database:
    image: redis:6.0-alpine
